name: Deploy to Firebase

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '13'

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run build -- --prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_STEGAPP_BFF11 }}'
          channelId: live
          projectId: stegapp-bff11
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
